### ISSUE TITLE
form not sending data

### ISSUE THREAD

**Issue by trajano** [artilleryio/artillery-core#224]
I am trying to send this data over
```
      - post:
          url: "/logout"
          form:
            token: {{ refresh_token }}
            token_type_hint: refresh_token
          headers:
            Authorization: Basic XXXXXXXXXXXX
            Accept: application/json
            # Content-Type: application/x-www-form-urlencoded
            Origin: "{{ origin }}"
```

but with HTTP debug

```
| 2022-03-09T15:54:29.215Z http request: {
  "url": "https://api.pnb.devhaus.net/logout",
  "method": "POST",
  "headers": {
    "user-agent": "Artillery (https://artillery.io)",
    "authorization": "Basic XXXXXXXX"
    "accept": "application/json",
    "origin": "https://localhost:3000"
  }
}
```
I don't see the form body in the request the others have "json" this happens to be form encoding only.
